name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: cypress-io/github-action@v5
        with:
		   fetch-depth: 0
      - run: npm i
      - run: npm run start $
      - run: npx cypress run	  
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5	
        with:
		  fetch-depth: 0
      - uses: 
        with: wagoid/commitlint-github-action@v5
		  token: ${{ secrets.GITHUB_TOKEN }}
